# Generated by Django 6.0.3 on 2026-03-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='company',
            field=models.CharField(choices=[('TCS', 'TCS'), ('WIPRO', 'Wipro'), ('INFOSYS', 'Infosys'), ('ACCENTURE', 'Accenture')], default='TCS', max_length=50),
        ),
    ]
