# Generated by Django 6.0.3 on 2026-03-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_question_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('QUANT', 'Quantitative'), ('REASON', 'Reasoning'), ('VERBAL', 'Verbal')], default='TCS', max_length=50),
            preserve_default=False,
        ),
    ]
