# Generated by Django 6.0.3 on 2026-03-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_question_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='date',
            new_name='created_at',
        ),
    ]
